package ExceptionHandlingdemo;

import java.util.Scanner;

public class ThrowDemo {
int rollno,age;
String Name;
Scanner sc=new Scanner(System.in);
public void accept()
{
	System.out.println("Enter Rollno");
	rollno=sc.nextInt();
	
	System.out.println("Enter name");
	Name=sc.nextLine();
	sc.nextLine();
	
	System.out.println("Enter age");
	age=sc.nextInt();
	if(age>=18)
	{
		try {
			throw new InvalidAgeExcetion();
		} catch (InvalidAgeExcetion e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ThrowDemo oo=new ThrowDemo();
		oo.accept();
	}

}
